package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {
     private byte idcategorie;
     private String nom;
     private String description;
     private Set medicaments = new HashSet(0);

    public Categorie() {    }	
    
    public Categorie(byte idcategorie, String nom) {
        this.idcategorie = idcategorie;
        this.nom = nom;
    }
    public Categorie(byte idcategorie, String nom, String description, Set medicaments) {
       this.idcategorie = idcategorie;
       this.nom = nom;
       this.description = description;
       this.medicaments = medicaments;
    }   
    public byte getIdcategorie() {
        return this.idcategorie;
    }    
    public void setIdcategorie(byte idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNom() {
        return this.nom;
    }    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMedicaments() {
        return this.medicaments;
    }    
    public void setMedicaments(Medicament medicament) {
        this.medicaments.add(medicament);
    }

    @Override
    public String toString() {
        String str = "Categorie{" + idcategorie + ", " + nom + ", " + description + ", ";
        for (Object line : medicaments) {
            str+= line.toString();
        }
        return str+ '}';
    }    
}


