package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1
/**
 * Consultation generated by hbm2java
 */
public class Consultation  implements java.io.Serializable {
     private ConsultationId id;
     private Docteur docteur;
     private Dossierpatient dossierpatient;
     private Ordonnance ordonnance;
     private String diagnostic;

    public Consultation() {    }
    public Consultation(ConsultationId id, Docteur docteur, Dossierpatient dossierpatient, Ordonnance ordonnance, String diagnostic) {
       this.id = id;
       this.docteur = docteur;
       this.dossierpatient = dossierpatient;
       this.ordonnance = ordonnance;
       this.diagnostic = diagnostic;
    }   
    public ConsultationId getId() {
        return this.id;
    }    
    public void setId(ConsultationId id) {
        this.id = id;
    }
    public Docteur getDocteur() {
        return this.docteur;
    }    
    public void setDocteur(Docteur docteur) {
        this.docteur = docteur;
    }
    public Dossierpatient getDossierpatient() {
        return this.dossierpatient;
    }    
    public void setDossierpatient(Dossierpatient dossierpatient) {
        this.dossierpatient = dossierpatient;
    }
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }
    public String getDiagnostic() {
        return this.diagnostic;
    }    
    public void setDiagnostic(String diagnostic) {
        this.diagnostic = diagnostic;
    }

    @Override
    public String toString() {
        return "Consultation{" + "id=" + id + ", docteur=" + docteur + ", dossierpatient=" + dossierpatient + ", ordonnance=" + ordonnance + ", diagnostic=" + diagnostic + '}';
    }
    
}


