package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
/**
 * Docteur generated by hbm2java
 */
public class Docteur  implements java.io.Serializable {
     private String matricule;
     private Specialite specialite;
     private String nomm;
     private String prenomm;
     private String ville;
     private String adresse;
     private String niveau;
     private Short nbrpatients;
     private Set dossierpatients = new HashSet(0);
     private Set consultations = new HashSet(0);

    public Docteur() {    }	
    public Docteur(String matricule, Specialite specialite, String nomm, String prenomm) {
        this.matricule = matricule;
        this.specialite = specialite;
        this.nomm = nomm;
        this.prenomm = prenomm;
    }
    public Docteur(String matricule, Specialite specialite, String nomm, String prenomm, String ville, String adresse, String niveau, Short nbrpatients, Set dossierpatients, Set consultations) {
       this.matricule = matricule;
       this.specialite = specialite;
       this.nomm = nomm;
       this.prenomm = prenomm;
       this.ville = ville;
       this.adresse = adresse;
       this.niveau = niveau;
       this.nbrpatients = nbrpatients;
       this.dossierpatients = dossierpatients;
       this.consultations = consultations;
    }   
    public String getMatricule() {
        return this.matricule;
    }    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Specialite getSpecialite() {
        return this.specialite;
    }    
    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }
    public String getNomm() {
        return this.nomm;
    }    
    public void setNomm(String nomm) {
        this.nomm = nomm;
    }
    public String getPrenomm() {
        return this.prenomm;
    }    
    public void setPrenomm(String prenomm) {
        this.prenomm = prenomm;
    }
    public String getVille() {
        return this.ville;
    }    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getAdresse() {
        return this.adresse;
    }    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getNiveau() {
        return this.niveau;
    }    
    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }
    public Short getNbrpatients() {
        return this.nbrpatients;
    }    
    public void setNbrpatients(Short nbrpatients) {
        this.nbrpatients = nbrpatients;
    }
    public Set getDossierpatients() {
        return this.dossierpatients;
    }    
    public void setDossierpatients(Dossierpatient dossierpatient) {
        this.dossierpatients.add(dossierpatient);
    }
    public Set getConsultations() {
        return this.consultations;
    }    
    public void setConsultations(Consultation consultation) {
        this.consultations.add(consultations);
    }

    @Override
    public String toString() {
        return "Docteur{" + matricule + ", " + nomm + ", " + prenomm + ", " + ville + ", " + adresse + ", " + niveau + ", " + nbrpatients + ", ";

        //return "Docteur{" + matricule + ", " + specialite.toString() + ", " + nomm + ", " + prenomm + ", " + ville + ", " + adresse + ", " + niveau + ", " + nbrpatients + ", ";
        //+ dossierpatients.toString() + ", consultations=" + consultations + '}';
    }
    
}