package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
/**
 * Medicament generated by hbm2java
 */
public class Medicament  implements java.io.Serializable {
     private int idmed;
     private Categorie categorie;
     private String nommed;
     private BigDecimal prix;
     private Set ordonnancemedicamentses = new HashSet(0);

    public Medicament() {    }	
    public Medicament(int idmed, Categorie categorie, String nommed) {
        this.idmed = idmed;
        this.categorie = categorie;
        this.nommed = nommed;
    }
    public Medicament(int idmed, Categorie categorie, String nommed, BigDecimal prix, Set ordonnancemedicamentses) {
       this.idmed = idmed;
       this.categorie = categorie;
       this.nommed = nommed;
       this.prix = prix;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }   
    public int getIdmed() {
        return this.idmed;
    }    
    public void setIdmed(int idmed) {
        this.idmed = idmed;
    }
    public Categorie getCategorie() {
        return this.categorie;
    }    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }
    public String getNommed() {
        return this.nommed;
    }    
    public void setNommed(String nommed) {
        this.nommed = nommed;
    }
    public BigDecimal getPrix() {
        return this.prix;
    }    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }
    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }    
    public void setOrdonnancemedicamentses(Ordonnancemedicaments ordonnancemedicament) {
        this.ordonnancemedicamentses.add(ordonnancemedicamentses);
    }

    @Override
    public String toString() {
        //return "Medicament{" + "idmed=" + idmed + ", categorie=" + categorie + ", nommed=" + nommed + ", prix=" + prix + ", ordonnancemedicamentses=" + ordonnancemedicamentses + '}';
        return "Medicament{" + "idmed=" + idmed + ", categorie=" + categorie + ", nommed=" + nommed + ", prix=" + prix + "}";
    }
    
}