package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

/**
 * OrdonnancechirurgieId generated by hbm2java
 */
public class OrdonnancechirurgieId implements java.io.Serializable {
    private int numord;
    private byte rang;
    public OrdonnancechirurgieId() {
    }
    public OrdonnancechirurgieId(int numord, byte rang) {
        this.numord = numord;
        this.rang = rang;
    }
    public int getNumord() {
        return this.numord;
    }
    public void setNumord(int numord) {
        this.numord = numord;
    }
    public byte getRang() {
        return this.rang;
    }
    public void setRang(byte rang) {
        this.rang = rang;
    }
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof OrdonnancechirurgieId)) {
            return false;
        }
        OrdonnancechirurgieId castOther = (OrdonnancechirurgieId) other;

        return (this.getNumord() == castOther.getNumord())
                && (this.getRang() == castOther.getRang());
    }
   public int hashCode() {
        int result = 17;

        result = 37 * result + this.getNumord();
        result = 37 * result + this.getRang();
        return result;
    }
}
