package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance  implements java.io.Serializable {
     private int numord;
     private String recommandation;
     private String typeo;
     private Date datec;
     private Set ordonnancechirurgies = new HashSet(0);
     private Set consultations = new HashSet(0);
     private Set ordonnancemedicamentses = new HashSet(0);
    public Ordonnance() {
    }
    public Ordonnance(int numord) {
        this.numord = numord;
    }
    public Ordonnance(int numord, String recommandation, String typeo, Date datec, Set ordonnancechirurgies, Set consultations, Set ordonnancemedicamentses) {
       this.numord = numord;
       this.recommandation = recommandation;
       this.typeo = typeo;
       this.datec = datec;
       this.ordonnancechirurgies = ordonnancechirurgies;
       this.consultations = consultations;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
    public int getNumord() {
        return this.numord;
    }
    public void setNumord(int numord) {
        this.numord = numord;
    }
    public String getRecommandation() {
        return this.recommandation;
    }
    public void setRecommandation(String recommandation) {
        this.recommandation = recommandation;
    }
    public String getTypeo() {
        return this.typeo;
    }
    public void setTypeo(String typeo) {
        this.typeo = typeo;
    }
    public Date getDatec() {
        return this.datec;
    }
    public void setDatec(Date datec) {
        this.datec = datec;
    }
    public Set getOrdonnancechirurgies() {
        return this.ordonnancechirurgies;
    }
    public void setOrdonnancechirurgies(Ordonnancechirurgie ordonnancechirurgie) {
        this.ordonnancechirurgies.add(ordonnancechirurgie);
    }
    public Set getConsultations() {
        return this.consultations;
    }
    public void setConsultations(Consultation consultation) {
        this.consultations.add(consultations);
    }
    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    public void setOrdonnancemedicamentses(Ordonnancemedicaments ordonnancemedicaments) {
        this.ordonnancemedicamentses.add(ordonnancemedicaments);
    }
}