package entities;
// Generated 2019-04-17 16:56:23 by Hibernate Tools 4.3.1

/**
 * OrdonnancemedicamentsId generated by hbm2java
 */
public class OrdonnancemedicamentsId implements java.io.Serializable {

    private int numord;
    private int idmed;

    public OrdonnancemedicamentsId() {
    }
    public OrdonnancemedicamentsId(int numord, int idmed) {
        this.numord = numord;
        this.idmed = idmed;
    }
    public int getNumord() {
        return this.numord;
    }
    public void setNumord(int numord) {
        this.numord = numord;
    }
    public int getIdmed() {
        return this.idmed;
    }
    public void setIdmed(int idmed) {
        this.idmed = idmed;
    }
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof OrdonnancemedicamentsId)) {
            return false;
        }
        OrdonnancemedicamentsId castOther = (OrdonnancemedicamentsId) other;

        return (this.getNumord() == castOther.getNumord())
                && (this.getIdmed() == castOther.getIdmed());
    }
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getNumord();
        result = 37 * result + this.getIdmed();
        return result;
    }
}